### ISSUE TITLE
Auto backup scripts for databases

### ISSUE THREAD

**Issue by ffamilyfriendly** [ffamilyfriendly/Thread-Watcher#71]
Right now all the backups are handled manually. Probably a good idea to automate this

**Comment by kmcbride3** [comment]
For consideration - moving the SQLite `data.db` file into its own directory, instead of creating it in the root directory, would allow docker builds to create a persistent volume link to the directory, which would expose `data.db` to the host system, and prevent it from being wiped when the container is destroyed and/or rebuilt.

This would add some complications, in that to maintain backwards compatibility, we'd then need to check if there is an already existing `data.db` file in the root directory, and if so, move it to the new folder first before attempting to read/write to it.

The upshot is that having the DB in its own directory would keep things cleaner should you opt to save copies of the DB periodically to ward against corruption and/or as a staging step as part of automating backups elsewhere.

**Comment by ffamilyfriendly** [comment]
> 

I'll probably add a database path option when I rewrite the configuration handling for #75. This would allow people to choose their own database folder.

I'll probably default it to ./data/data.db to keep it working good for the docker peeps but if left blank it'll assume  the database is in the root folder

**Comment by ffamilyfriendly** [comment]
fixed in [e63930a](https://github.com/ffamilyfriendly/Thread-Watcher/commit/e63930a7518c22e227d6c634fe495aa46cb57784)
